// SAMPLE: the accounts and events in the sample clients' markets, the
// Phoenix area and northern Arizona. After the move these come from the
// nightly jobs: Google for the accounts, and Eventbrite, convention
// centers, tourism boards, chambers, universities, Ticketmaster, wedding
// shows and tournaments for the events. Every business and person here is
// made up.

import type { Account, EventLead } from "./types";

const DAY = 86_400_000;
const AZ = 7 * 3_600_000;

/** A time in Arizona, `days` from today. */
export function azAt(now: Date, days: number, hour = 9, minute = 0) {
  const local = new Date(now.getTime() - AZ);
  return new Date(
    Date.UTC(
      local.getUTCFullYear(),
      local.getUTCMonth(),
      local.getUTCDate() + days,
      hour,
      minute,
    ) + AZ,
  ).toISOString();
}

/** This morning's 6:00 in Arizona, when the nightly jobs finish. */
export function lastRun(now: Date) {
  const today = azAt(now, 0, 6);
  return new Date(today) <= now
    ? today
    : new Date(new Date(today).getTime() - DAY).toISOString();
}

export const CITIES: Record<string, { lat: number; lng: number }> = {
  Phoenix: { lat: 33.4484, lng: -112.074 },
  Scottsdale: { lat: 33.4942, lng: -111.9261 },
  "Paradise Valley": { lat: 33.5312, lng: -111.9426 },
  Tempe: { lat: 33.4255, lng: -111.94 },
  Mesa: { lat: 33.4152, lng: -111.8315 },
  Chandler: { lat: 33.3062, lng: -111.8413 },
  Gilbert: { lat: 33.3528, lng: -111.789 },
  Glendale: { lat: 33.5387, lng: -112.186 },
  "Fountain Hills": { lat: 33.6117, lng: -111.7174 },
  Sedona: { lat: 34.8697, lng: -111.761 },
  Cottonwood: { lat: 34.7392, lng: -112.0099 },
  Flagstaff: { lat: 35.1983, lng: -111.6513 },
  Tucson: { lat: 32.2226, lng: -110.9747 },
};

const near = (city: keyof typeof CITIES, dLat: number, dLng: number) => ({
  city,
  lat: CITIES[city].lat + dLat,
  lng: CITIES[city].lng + dLng,
});

export function sampleAccounts(now: Date): Account[] {
  const found = (days: number) => azAt(now, -days, 6);
  const fresh = lastRun(now);

  return [
    {
      kind: "ACCOUNT",
      id: "camelback-grand",
      name: "Camelback Grand Resort",
      category: "HOTEL",
      ...near("Scottsdale", 0.008, 0.012),
      address: "6800 E Camelback Rd, Scottsdale",
      rating: 4.6,
      reviews: 2840,
      phone: "(480) 555-0141",
      website: "camelbackgrand.example",
      carService: "HAS",
      carServiceNote: "Their site lists a house car for guests within 5 miles",
      note: "400 rooms and 30,000 square feet of meeting space, so conference groups are a big part of their year.",
      foundAt: found(41),
      contact: {
        name: "Natalie Brooks",
        title: "Director of Sales",
        email: "natalie.brooks@camelbackgrand.example",
        phone: "(480) 555-0142",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "saguaro-ridge",
      name: "Saguaro Ridge Inn & Spa",
      category: "HOTEL",
      ...near("Paradise Valley", 0.004, -0.01),
      address: "5402 E Lincoln Dr, Paradise Valley",
      rating: 4.7,
      reviews: 1210,
      phone: "(480) 555-0117",
      website: "saguaroridge.example",
      carService: "NONE",
      note: "A spa resort. Guests fly in for long weekends and rarely rent a car.",
      foundAt: fresh,
      contact: {
        name: "Marco Vitale",
        title: "Chief Concierge",
        email: "marco.vitale@saguaroridge.example",
        phone: "(480) 555-0118",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "copper-canyon-suites",
      name: "Copper Canyon Suites Downtown",
      category: "HOTEL",
      ...near("Phoenix", 0.002, 0.003),
      address: "201 N 3rd St, Phoenix",
      rating: 4.3,
      reviews: 1960,
      phone: "(602) 555-0123",
      website: "coppercanyonsuites.example",
      carService: "NONE",
      note: "Two blocks from the convention center, so it fills up for every big show.",
      foundAt: found(63),
      contact: {
        name: "Aisha Patel",
        title: "Director of Sales",
        email: "aisha.patel@coppercanyonsuites.example",
        phone: "(602) 555-0124",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "mesa-riverview",
      name: "Mesa Riverview Hotel",
      category: "HOTEL",
      ...near("Mesa", 0.02, -0.04),
      address: "1011 W Riverview Dr, Mesa",
      rating: 4.2,
      reviews: 870,
      phone: "(480) 555-0131",
      website: "mesariverview.example",
      carService: "UNKNOWN",
      note: "Next to the spring training ballpark, so March is their busiest month.",
      foundAt: found(12),
      contact: {
        name: "Derek Owens",
        title: "General Manager",
        email: "dowens@mesariverview.example",
        verified: false,
      },
    },
    {
      kind: "ACCOUNT",
      id: "tempe-lakeside",
      name: "Tempe Lakeside Hotel",
      category: "HOTEL",
      ...near("Tempe", 0.006, 0.004),
      address: "60 E Rio Salado Pkwy, Tempe",
      rating: 4.4,
      reviews: 1530,
      phone: "(480) 555-0152",
      website: "tempelakeside.example",
      carService: "NONE",
      note: "Next to the university and the lake: visiting families and corporate groups all year.",
      foundAt: fresh,
      contact: {
        name: "Hannah Kim",
        title: "Front Office Manager",
        email: "hannah.kim@tempelakeside.example",
        phone: "(480) 555-0153",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "red-rock-vista",
      name: "Red Rock Vista Lodge",
      category: "HOTEL",
      ...near("Sedona", -0.004, 0.006),
      address: "160 Portal Ln, Sedona",
      rating: 4.8,
      reviews: 990,
      phone: "(928) 555-0161",
      website: "redrockvista.example",
      carService: "NONE",
      note: "Most guests drive up from Sky Harbor, two hours away. Many would rather be driven.",
      foundAt: found(20),
      contact: {
        name: "Elena Ruiz",
        title: "Concierge Manager",
        email: "elena.ruiz@redrockvista.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "chandler-fashion-suites",
      name: "Chandler Fashion Suites",
      category: "HOTEL",
      ...near("Chandler", 0.0, -0.04),
      address: "3300 W Chandler Blvd, Chandler",
      rating: 4.1,
      reviews: 640,
      phone: "(480) 555-0171",
      website: "chandlerfashionsuites.example",
      carService: "NONE",
      foundAt: found(4),
    },
    {
      kind: "ACCOUNT",
      id: "glendale-stadium-suites",
      name: "Glendale Stadium Suites",
      category: "HOTEL",
      ...near("Glendale", -0.03, -0.07),
      address: "9400 W Maryland Ave, Glendale",
      rating: 4.2,
      reviews: 1340,
      phone: "(623) 555-0181",
      website: "glendalestadiumsuites.example",
      carService: "UNKNOWN",
      note: "Across from the stadium, so every game and concert fills it.",
      foundAt: found(9),
      contact: {
        name: "Carlos Medina",
        title: "Group Sales Manager",
        email: "carlos.medina@glendalestadiumsuites.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "fountain-hills-resort",
      name: "Fountain Hills Lakeview Resort",
      category: "HOTEL",
      ...near("Fountain Hills", 0.002, 0.004),
      address: "16800 E El Lago Blvd, Fountain Hills",
      rating: 4.5,
      reviews: 940,
      phone: "(480) 555-0191",
      website: "fhlakeview.example",
      carService: "NONE",
      foundAt: fresh,
    },
    {
      kind: "ACCOUNT",
      id: "flagstaff-mountain-lodge",
      name: "Flagstaff Mountain Lodge",
      category: "HOTEL",
      ...near("Flagstaff", -0.004, -0.02),
      address: "1175 W Route 66, Flagstaff",
      rating: 4.4,
      reviews: 1480,
      phone: "(928) 555-0102",
      website: "flagstaffmountainlodge.example",
      carService: "NONE",
      note: "Ski season and Grand Canyon trips keep it full from December to March.",
      foundAt: fresh,
      contact: {
        name: "Megan Hart",
        title: "Director of Sales",
        email: "megan.hart@flagstaffmountainlodge.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "desert-willow",
      name: "Desert Willow Estate",
      category: "VENUE",
      ...near("Scottsdale", 0.22, 0.05),
      address: "10040 E Happy Valley Rd, Scottsdale",
      rating: 4.9,
      reviews: 410,
      phone: "(480) 555-0144",
      website: "desertwillowestate.example",
      carService: "NONE",
      note: "About 120 weddings a year, mostly couples flying in from out of state.",
      foundAt: found(30),
      contact: {
        name: "Jasmine Carter",
        title: "Venue Coordinator",
        email: "jasmine@desertwillowestate.example",
        phone: "(480) 555-0145",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "ironwood-ballroom",
      name: "The Ironwood Ballroom",
      category: "VENUE",
      ...near("Phoenix", 0.001, 0.0),
      address: "1 N Central Ave, Phoenix",
      rating: 4.6,
      reviews: 380,
      phone: "(602) 555-0133",
      website: "ironwoodballroom.example",
      carService: "NONE",
      foundAt: found(55),
      contact: {
        name: "Victor Huang",
        title: "Events Manager",
        email: "victor@ironwoodballroom.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "sonoran-bloom",
      name: "Sonoran Bloom Gardens",
      category: "VENUE",
      ...near("Gilbert", 0.01, 0.02),
      address: "2757 E Guadalupe Rd, Gilbert",
      rating: 4.8,
      reviews: 520,
      phone: "(480) 555-0164",
      website: "sonoranbloom.example",
      carService: "HAS",
      carServiceNote: "Their vendor page recommends one shuttle company",
      foundAt: found(90),
      contact: {
        name: "Rachel Moreno",
        title: "Venue Director",
        email: "rachel@sonoranbloom.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "mesa-arts-pavilion",
      name: "Mesa Arts Pavilion",
      category: "VENUE",
      ...near("Mesa", 0.0, 0.0),
      address: "1 E Main St, Mesa",
      rating: 4.5,
      reviews: 2310,
      phone: "(480) 555-0135",
      website: "mesaartspavilion.example",
      carService: "NONE",
      foundAt: found(6),
      contact: {
        name: "Tom Becker",
        title: "Events Director",
        email: "tbecker@mesaartspavilion.example",
        verified: false,
      },
    },
    {
      kind: "ACCOUNT",
      id: "northern-pines-barn",
      name: "Northern Pines Wedding Barn",
      category: "VENUE",
      ...near("Flagstaff", 0.06, -0.03),
      address: "5200 N Fort Valley Rd, Flagstaff",
      rating: 4.9,
      reviews: 260,
      phone: "(928) 555-0107",
      website: "northernpinesbarn.example",
      carService: "NONE",
      note: "Summer weddings in the pines. Guests stay in Flagstaff hotels 15 minutes away.",
      foundAt: found(2),
      contact: {
        name: "Lily Tran",
        title: "Owner",
        email: "lily@northernpinesbarn.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "valley-semiconductor",
      name: "Valley Semiconductor",
      category: "CORPORATE",
      ...near("Chandler", -0.01, 0.06),
      address: "4500 S Price Rd, Chandler",
      rating: 3.9,
      reviews: 210,
      phone: "(480) 555-0174",
      website: "valleysemi.example",
      carService: "NONE",
      note: "Engineers and customers fly in from Taiwan and Texas most weeks.",
      foundAt: fresh,
      contact: {
        name: "Sunita Rao",
        title: "Global Travel Manager",
        email: "sunita.rao@valleysemi.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "sun-corridor-health",
      name: "Sun Corridor Health Partners",
      category: "CORPORATE",
      ...near("Phoenix", 0.035, 0.002),
      address: "2400 N Central Ave, Phoenix",
      rating: 4.0,
      reviews: 150,
      phone: "(602) 555-0127",
      website: "suncorridorhealth.example",
      carService: "UNKNOWN",
      foundAt: found(1),
      contact: {
        name: "Greg Lawson",
        title: "Executive Assistant to the CEO",
        email: "glawson@suncorridorhealth.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "northbank-financial",
      name: "Northbank Financial",
      category: "CORPORATE",
      ...near("Tempe", 0.004, -0.03),
      address: "1600 W Rio Salado Pkwy, Tempe",
      rating: 4.2,
      reviews: 95,
      phone: "(480) 555-0156",
      website: "northbankfinancial.example",
      carService: "NONE",
      foundAt: found(15),
      contact: {
        name: "Laura Chen",
        title: "Corporate Travel Manager",
        email: "laura.chen@northbankfinancial.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "apex-aerospace",
      name: "Apex Aerospace Systems",
      category: "CORPORATE",
      ...near("Mesa", 0.04, 0.07),
      address: "4800 E Falcon Dr, Mesa",
      rating: 4.3,
      reviews: 120,
      phone: "(480) 555-0137",
      website: "apexaerospace.example",
      carService: "NONE",
      note: "Defense customers visit every month and fly into Mesa Gateway or Sky Harbor.",
      foundAt: found(14),
      contact: {
        name: "Mike Delgado",
        title: "Office Manager",
        email: "mdelgado@apexaerospace.example",
        phone: "(480) 555-0138",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "harlow-vance",
      name: "Harlow & Vance LLP",
      category: "LAW",
      ...near("Phoenix", 0.0, 0.001),
      address: "2 N Central Ave, Suite 1800, Phoenix",
      rating: 4.8,
      reviews: 88,
      phone: "(602) 555-0129",
      website: "harlowvance.example",
      carService: "NONE",
      foundAt: found(70),
      contact: {
        name: "Patricia Gomez",
        title: "Office Manager",
        email: "pgomez@harlowvance.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "rios-gutierrez",
      name: "Rios Gutierrez Law Group",
      category: "LAW",
      ...near("Scottsdale", 0.005, 0.0),
      address: "7135 E Camelback Rd, Scottsdale",
      rating: 4.9,
      reviews: 140,
      phone: "(480) 555-0148",
      website: "riosgutierrez.example",
      carService: "NONE",
      foundAt: fresh,
      contact: {
        name: "Daniel Rios",
        title: "Managing Partner",
        email: "daniel@riosgutierrez.example",
        verified: false,
      },
    },
    {
      kind: "ACCOUNT",
      id: "evergreen-desert",
      name: "Evergreen Desert Funeral Home",
      category: "FUNERAL",
      ...near("Mesa", 0.0, -0.02),
      address: "555 W Main St, Mesa",
      rating: 4.7,
      reviews: 310,
      phone: "(480) 555-0139",
      website: "evergreendesert.example",
      carService: "NONE",
      carServiceNote: "They own a hearse but list no family limousine",
      foundAt: found(10),
      contact: {
        name: "Robert Hayes",
        title: "Funeral Director",
        email: "rhayes@evergreendesert.example",
        phone: "(480) 555-0140",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "saguaro-memorial",
      name: "Saguaro Memorial Chapel",
      category: "FUNERAL",
      ...near("Phoenix", 0.09, -0.01),
      address: "1800 W Glendale Ave, Phoenix",
      rating: 4.6,
      reviews: 240,
      phone: "(602) 555-0119",
      website: "saguaromemorial.example",
      carService: "UNKNOWN",
      foundAt: found(33),
    },
    {
      kind: "ACCOUNT",
      id: "pinnacle-peak-cc",
      name: "Pinnacle Peak Country Club",
      category: "GOLF",
      ...near("Scottsdale", 0.21, 0.03),
      address: "8701 E Pinnacle Peak Rd, Scottsdale",
      rating: 4.6,
      reviews: 330,
      phone: "(480) 555-0146",
      website: "pinnaclepeakcc.example",
      carService: "NONE",
      foundAt: found(25),
      contact: {
        name: "Steve Morrison",
        title: "Director of Membership",
        email: "smorrison@pinnaclepeakcc.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "ahwatukee-ridge",
      name: "Ahwatukee Ridge Golf Club",
      category: "GOLF",
      ...near("Phoenix", -0.12, 0.09),
      address: "12432 S 48th St, Phoenix",
      rating: 4.3,
      reviews: 610,
      phone: "(480) 555-0126",
      website: "ahwatukeeridge.example",
      carService: "HAS",
      carServiceNote: "They run their own member shuttle van",
      foundAt: found(48),
      contact: {
        name: "Kelly Brennan",
        title: "Events Director",
        email: "kelly@ahwatukeeridge.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "mesquite-flats",
      name: "Mesquite Flats Casino Resort",
      category: "CASINO",
      ...near("Chandler", -0.05, -0.11),
      address: "8000 S Gila River Rd, Chandler",
      rating: 4.4,
      reviews: 5200,
      phone: "(480) 555-0176",
      website: "mesquiteflats.example",
      carService: "NONE",
      note: "Their hosts comp rides for top players and pay for them by the trip today.",
      foundAt: found(3),
      contact: {
        name: "Andre Wallace",
        title: "VIP Host Manager",
        email: "andre.wallace@mesquiteflats.example",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "harmony-grove",
      name: "Harmony Grove Senior Living",
      category: "SENIOR",
      ...near("Gilbert", -0.04, 0.02),
      address: "3155 S Val Vista Dr, Gilbert",
      rating: 4.5,
      reviews: 180,
      phone: "(480) 555-0166",
      website: "harmonygrove.example",
      carService: "NONE",
      foundAt: found(16),
      contact: {
        name: "Diane Foster",
        title: "Life Enrichment Director",
        email: "diane.foster@harmonygrove.example",
        phone: "(480) 555-0167",
        verified: true,
      },
    },
    {
      kind: "ACCOUNT",
      id: "verde-valley-wine",
      name: "Verde Valley Wine Trail Co.",
      category: "TOURS",
      ...near("Cottonwood", 0.002, 0.003),
      address: "1101 N Main St, Cottonwood",
      rating: 4.9,
      reviews: 760,
      phone: "(928) 555-0168",
      website: "verdewinetrail.example",
      carService: "NONE",
      foundAt: found(8),
      contact: {
        name: "Sam Whitaker",
        title: "Owner",
        email: "sam@verdewinetrail.example",
        verified: true,
      },
    },
  ];
}

export function sampleEvents(now: Date): EventLead[] {
  const at = (days: number, hour: number, minute = 0) =>
    azAt(now, days, hour, minute);
  const found = (days: number) => azAt(now, -days, 6);
  const fresh = lastRun(now);

  return [
    {
      kind: "EVENT",
      id: "valley-heart-ball",
      name: "Valley Heart Ball",
      type: "GALA",
      source: "EVENTBRITE",
      ...near("Phoenix", 0.002, 0.003),
      venue: "Copper Canyon Suites Downtown",
      organizer: "Valley Heart Foundation",
      guests: 600,
      date: at(9, 18),
      note: "Black tie. Last year's sponsors included three of the Valley's biggest employers.",
      foundAt: found(21),
      website: "valleyheartfoundation.example",
      contact: {
        name: "Monica Reyes",
        title: "Development Director",
        email: "monica@valleyheartfoundation.example",
        phone: "(602) 555-0185",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "arizona-tech-summit",
      name: "Arizona Tech Summit",
      type: "CONFERENCE",
      source: "CONVENTION",
      ...near("Phoenix", 0.003, 0.005),
      venue: "Downtown Convention Center",
      organizer: "Arizona Technology Alliance",
      guests: 2500,
      date: at(23, 8),
      endDate: at(25, 17),
      note: "Three days, with 60 speakers flying in.",
      foundAt: found(17),
      contact: {
        name: "Jordan Ellis",
        title: "Event Manager",
        email: "jordan.ellis@aztechalliance.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "scottsdale-bridal-show",
      name: "Scottsdale Spring Bridal Show",
      type: "WEDDING_SHOW",
      source: "WEDDING",
      ...near("Scottsdale", 0.008, 0.012),
      venue: "Camelback Grand Resort",
      organizer: "Desert Bride Events",
      guests: 1200,
      date: at(40, 11),
      foundAt: fresh,
      contact: {
        name: "Tara Collins",
        title: "Show Producer",
        email: "tara@desertbride.example",
        phone: "(480) 555-0188",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "sonoran-founders-dinner",
      name: "Sonoran Founders Dinner",
      type: "BUSINESS",
      source: "CHAMBER",
      ...near("Paradise Valley", 0.004, -0.01),
      venue: "Saguaro Ridge Inn & Spa",
      organizer: "North Valley Chamber of Commerce",
      guests: 250,
      date: at(12, 18, 30),
      foundAt: found(11),
      contact: {
        name: "Paul Nguyen",
        title: "Events Director",
        email: "paul@northvalleychamber.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "valley-state-commencement",
      name: "Valley State University Winter Commencement",
      type: "GRADUATION",
      source: "UNIVERSITY",
      ...near("Tempe", 0.0, 0.01),
      venue: "University Arena",
      organizer: "Valley State University",
      guests: 9000,
      date: at(64, 10),
      phone: "(480) 555-0158",
      foundAt: found(5),
    },
    {
      kind: "EVENT",
      id: "desert-classic-pro-am",
      name: "Desert Classic Charity Pro-Am",
      type: "TOURNAMENT",
      source: "TOURNAMENT",
      ...near("Scottsdale", 0.21, 0.03),
      venue: "Pinnacle Peak Country Club",
      organizer: "Desert Classic Foundation",
      guests: 400,
      date: at(30, 7, 30),
      endDate: at(32, 16),
      foundAt: found(13),
      contact: {
        name: "Greg Sutton",
        title: "Tournament Director",
        email: "greg@desertclassic.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "midnight-coyotes",
      name: "Midnight Coyotes, live",
      type: "CONCERT",
      source: "TICKETMASTER",
      ...near("Glendale", -0.03, -0.065),
      venue: "Desert Sky Arena",
      organizer: "Desert Sky Arena",
      guests: 18000,
      date: at(5, 19, 30),
      foundAt: found(3),
      contact: {
        name: "Nina Alvarez",
        title: "Premium Seating Manager",
        email: "nalvarez@desertskyarena.example",
        verified: false,
      },
    },
    {
      kind: "EVENT",
      id: "saguaro-sounds",
      name: "Saguaro Sounds Festival",
      type: "FESTIVAL",
      source: "TOURISM",
      ...near("Phoenix", 0.015, 0.0),
      venue: "Roosevelt Row Commons",
      organizer: "Saguaro Sounds",
      guests: 30000,
      date: at(18, 12),
      endDate: at(20, 23),
      foundAt: fresh,
      contact: {
        name: "Becca Lin",
        title: "VIP and Hospitality Lead",
        email: "becca@saguarosounds.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "healthcare-leaders-forum",
      name: "Healthcare Leaders Forum",
      type: "CONFERENCE",
      source: "CONVENTION",
      ...near("Scottsdale", 0.008, 0.012),
      venue: "Camelback Grand Resort",
      organizer: "Southwest Health Executives",
      guests: 800,
      date: at(33, 8),
      endDate: at(34, 15),
      foundAt: found(7),
      contact: {
        name: "Alan Pierce",
        title: "Conference Director",
        email: "apierce@swhealthexecs.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "mesa-arts-gala",
      name: "Mesa Arts Gala",
      type: "GALA",
      source: "EVENTBRITE",
      ...near("Mesa", 0.0, 0.0),
      venue: "Mesa Arts Pavilion",
      organizer: "East Valley Arts Council",
      guests: 300,
      date: at(3, 18),
      foundAt: found(19),
      contact: {
        name: "Grace Okafor",
        title: "Event Chair",
        email: "grace@eastvalleyarts.example",
        phone: "(480) 555-0136",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "gilbert-business-awards",
      name: "Gilbert Business Awards",
      type: "BUSINESS",
      source: "CHAMBER",
      ...near("Gilbert", 0.01, 0.02),
      venue: "Sonoran Bloom Gardens",
      organizer: "Gilbert Business Council",
      guests: 400,
      date: at(16, 18),
      foundAt: found(9),
      contact: {
        name: "Kevin Marsh",
        title: "Events Director",
        email: "kevin@gilbertbusiness.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "red-rock-film-week",
      name: "Red Rock Film Week",
      type: "FESTIVAL",
      source: "TOURISM",
      ...near("Sedona", 0.002, 0.004),
      venue: "Sedona Arts Theater",
      organizer: "Red Rock Film Society",
      guests: 6000,
      date: at(50, 10),
      endDate: at(56, 22),
      foundAt: found(6),
      contact: {
        name: "Olivia Grant",
        title: "Festival Director",
        email: "olivia@redrockfilm.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "desert-classic-auction",
      name: "Desert Classic Motorcar Auction",
      type: "AUCTION",
      source: "TOURISM",
      ...near("Scottsdale", 0.06, 0.02),
      venue: "Scottsdale Auction Pavilion",
      organizer: "Desert Classic Auctions",
      guests: 100000,
      date: at(85, 9),
      endDate: at(93, 21),
      note: "The biggest week of the year for black car in Scottsdale. Bidders book cars months ahead.",
      foundAt: found(24),
      contact: {
        name: "Ryan Cole",
        title: "VIP Bidder Relations",
        email: "ryan.cole@desertclassicauctions.example",
        phone: "(480) 555-0149",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "women-in-business-luncheon",
      name: "Valley Women in Business Luncheon",
      type: "BUSINESS",
      source: "EVENTBRITE",
      ...near("Tempe", 0.006, 0.004),
      venue: "Tempe Lakeside Hotel",
      organizer: "Valley Women in Business",
      guests: 220,
      date: at(7, 11, 30),
      foundAt: fresh,
      contact: {
        name: "Sofia Marquez",
        title: "Programs Director",
        email: "sofia@valleywomeninbusiness.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "restaurant-week-opening",
      name: "Phoenix Restaurant Week Opening Night",
      type: "FESTIVAL",
      source: "TOURISM",
      ...near("Phoenix", 0.001, 0.0),
      venue: "The Ironwood Ballroom",
      organizer: "Phoenix Restaurant Alliance",
      guests: 700,
      date: at(27, 19),
      phone: "(602) 555-0179",
      foundAt: found(2),
    },
    {
      kind: "EVENT",
      id: "arizona-realtors-convention",
      name: "Arizona Realtors Convention",
      type: "CONFERENCE",
      source: "CONVENTION",
      ...near("Mesa", 0.003, 0.004),
      venue: "East Valley Convention Center",
      organizer: "Arizona Realty Association",
      guests: 3000,
      date: at(45, 8),
      endDate: at(47, 17),
      foundAt: found(12),
      contact: {
        name: "Linda Park",
        title: "Meeting Planner",
        email: "lpark@azrealty.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "winter-lights-gala",
      name: "Winter Lights Gala",
      type: "GALA",
      source: "EVENTBRITE",
      ...near("Gilbert", 0.01, 0.02),
      venue: "Sonoran Bloom Gardens",
      organizer: "Gilbert Children's Hospital Foundation",
      guests: 450,
      date: at(58, 18),
      foundAt: found(4),
      contact: {
        name: "Heather Quinn",
        title: "Development Director",
        email: "hquinn@gilbertchildrens.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "stadium-lights-tour",
      name: "Stadium Lights Tour",
      type: "CONCERT",
      source: "TICKETMASTER",
      ...near("Glendale", -0.026, -0.06),
      venue: "Glendale Stadium",
      organizer: "Glendale Stadium",
      guests: 60000,
      date: at(38, 19),
      foundAt: found(1),
      contact: {
        name: "Dante Brooks",
        title: "Suites Manager",
        email: "dbrooks@glendalestadium.example",
        verified: true,
      },
    },
    {
      kind: "EVENT",
      id: "pine-ridge-commencement",
      name: "Pine Ridge University Commencement",
      type: "GRADUATION",
      source: "UNIVERSITY",
      ...near("Flagstaff", -0.01, 0.0),
      venue: "Pine Ridge Dome",
      organizer: "Pine Ridge University",
      guests: 7000,
      date: at(67, 10),
      phone: "(928) 555-0103",
      foundAt: found(5),
    },
  ];
}
